# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29872801d35249e428a0e4e3fae8b133578bf577fbdaa58e7891fa565c7d22f19d3b2a6d98cfba2211d03b928dad4803aa9665e2ddb3d89b74b2245319f04e4f

test:
  secret_key_base: 4021d0113d4319fab122bb19bb7fa608836be88c7f568aa1bca1467b947029362358bce6e4c7fb56425eb510044117c4ea26789aafc737c0685824d44c41f90b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
